### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by aditya-pushkar** [hoemotion/discord-mass-dm#19]
Application is not running after using valid proxies

**Comment by hoemotion** [comment]
Make sure the format is correct

**Comment by aditya-pushkar** [comment]
proxy:port
proxy:port
proxy:port

**Comment by hoemotion** [comment]
> proxy:port proxy:port proxy:port
> 
> Is This correct format ?

Yes if you dont use proxies which need an authentication

**Comment by GaryGallo1** [comment]
Is it works with socks5?
I entered in proxies.txt `username:password@ip:port` and choose socks5 in console, but getting:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 898, in start        
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_proto.py", line 213, in data_received 
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Expected HTTP/'
```

BWT, http works fine.
