### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nineVnine** [hoemotion/discord-mass-dm#24]
Traceback (most recent call last):
  File "C:\Users\z2551\OneDrive\Рабочий стол\tоken\discord-mass-dm-main\main.py", line 819, in <module>
    asyncio.get_event_loop().run_until_complete(client.start(first_start="true"))
  File "C:\Users\z2551\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\z2551\OneDrive\Рабочий стол\tоken\discord-mass-dm-main\main.py", line 651, in start
    self.stop()
  File "C:\Users\z2551\AppData\Local\Programs\Python\Python39\lib\site-packages\tasksio\__init__.py", line 23, in join
    await asyncio.gather(*self._tasks)
  File "C:\Users\z2551\OneDrive\Рабочий стол\tоken\discord-mass-dm-main\main.py", line 218, in setup
    fingerprint = jsonn["fingerprint"]
KeyError: 'fingerprint'

**Comment by S1mp1yDucky** [comment]
no clue why you have this error, try reinstalling packages which you can see in the "main.py" file.
