### ISSUE TITLE
Websocketapp isue

### ISSUE THREAD

**Issue by HMVOP** [hoemotion/discord-mass-dm#27]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from lib.scrape import scrape
  File "/home/runner/discord-mass-dm/lib/scrape.py", line 55, in <module>
    class DiscordSocket(websocket.WebSocketApp):
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

**Comment by S1mp1yDucky** [comment]
Use this to fix:

`pip install websocket-client`
