### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by S1mp1yDucky** [hoemotion/Discord-Mass-DM#32]
Traceback (most recent call last):
  File "C:\Users\S1mp1y Ducky\Documents\massdm2\main.py", line 526, in send
    response = await self.direct_message(token, channel, user, proxy)
  File "C:\Users\S1mp1y Ducky\Documents\massdm2\main.py", line 508, in direct_message
    code = json["code"]
KeyError: 'code'

**Comment by HugoLB0** [comment]
+1, got the same issue, captcha isnt solve

**Comment by HugoLB0** [comment]
need to fix the send to captcha part, I think its at line 509, need to add it correctly, for now the captcha isnt sent to the api endpoint

**Comment by Jacquesvdberg92** [comment]
Hello, so how do you actually fix this? I have the same issue, it creates but never send the message to the user

**Comment by hoemotion** [comment]
You guys really need to read the readme.md file, this tool was patched ages ago, the only reason I didn't archive it was that somebody might fix it and push a pr

**Comment by Jacquesvdberg92** [comment]
okay so no plan to fix it then, thanks for the repo regardless
